### ISSUE TITLE
"apply_cost" does not work correctly against shop_cart()

### ISSUE THREAD

**Issue by murwiz** [interchange/Dancer-Plugin-Interchange6#29]
Note:
...
shop_cart()->apply_cost( name => 'shipping', amount => 1.23 );
debug(shop_cart()->cost('shipping'));
...
Bad argument to cost: shipping 

If you dump out shop_cart()->costs, you see an empty array.

However, this works:

my $cart = shop_cart();
$cart->apply_cost( ... );

**Comment by SysPete** [comment]
Closed by commit 16afd053
