### ISSUE TITLE
$navigation->{count}, paging issues

### ISSUE THREAD

**Issue by hexfusion** [interchange/Dancer-Plugin-Interchange6#45]
The count iterator for the navigation route seems to be returning odd results.  Right now it basically returns the same result of pager.last vs $products->pager->total_count.  I believe this is causing issues with paging navigation menus.  Can I get clarification on what this should return.

**Comment by SysPete** [comment]
Performance problems were caused by the horrible joins used in older ic6s which have gone away since I switched over to using correlated subqueries for all of the resultset mathods.
@sbatschelet is this still an issue? Was your angler issue fixed in angler or in dpic6?
